# Makefile
#
# ============================================================================
# Copyright (c) Texas Instruments Inc 2009
#
# Use of this software is controlled by the terms and conditions found in the
# license agreement under which this software has been supplied or provided.
# ============================================================================

TARGET = $(notdir $(CURDIR))

VERBOSE = true

ifeq ($(VERBOSE), true)
    override VERBOSE =
else
    override VERBOSE = @
endif

-include $(DMAI_INSTALL_DIR)/Platform.make

# Package path for the XDC tools
XDC_PATH = $(USER_XDC_PATH);../../packages;$(DMAI_INSTALL_DIR)/packages;$(CE_INSTALL_DIR)/packages;$(FC_INSTALL_DIR)/packages;$(LINK_INSTALL_DIR)/packages;$(XDAIS_INSTALL_DIR)/packages;$(CMEM_INSTALL_DIR)/packages;$(CODEC_INSTALL_DIR)/packages;$(CE_INSTALL_DIR)/examples

# Where to output configuration files
XDC_CFG		= $(TARGET)_config

# Output compiler options
XDC_CFLAGS	= $(XDC_CFG)/compiler.opt

# Output linker file
XDC_LFILE	= $(XDC_CFG)/linker.cmd

# Input configuration file
XDC_CFGFILE	= $(TARGET).cfg

PLATFORM_OS		     = $(strip $(PLATFORM_OS_dm365_al))
PLATFORM_DEVICE		 = $(strip $(PLATFORM_DEVICE_dm365_al))
PLATFORM_PERIPHERALS = $(strip $(PLATFORM_PERIPHERALS_dm365_al))
PLATFORM_XDC_TARGET	 = $(strip $(PLATFORM_XDC_TARGET_dm365_al))
PLATFORM_XDC		 = $(strip $(PLATFORM_XDC_dm365_al))
TIMESTAMP_FILE = ./appl/include/timestamp_autogenerated.h

# The XDC configuration tool command line
CONFIGURO = $(XDC_INSTALL_DIR)/xs xdc.tools.configuro

C_FLAGS += -Wall -g -Iucgui/config -Iucgui/core -Iappl/include -Iappl/include/Task_UI

#LD_FLAGS += -lpthread -lpng -lz -ljpeg -lfreetype -lasound
LD_FLAGS += -lpthread -lasound
LD_FLAGS += -L$(LINUXLIBS_INSTALL_DIR)/lib

COMPILE.c = $(VERBOSE) $(CC) $(C_FLAGS) $(CPP_FLAGS) -c
LINK.c = $(VERBOSE) $(CC) $(LD_FLAGS)

SOURCES = $(wildcard *.c) $(wildcard appl/src/Task_UI/*.c) $(wildcard appl/src/*.c) $(wildcard appl/avi/*.c)
HEADERS = $(wildcard *.h) $(wildcard appl/include/*.h) $(wildcard appl/include/Task_UI/*.h) $(wildcard appl/avi/*.h)

SOURCES += $(wildcard appl/system-thread/decode/*.c) 
SOURCES += $(wildcard appl/system-thread/encode/*.c) 
HEADERS += $(wildcard appl/system-thread/decode/*.h) 
HEADERS += $(wildcard appl/system-thread/encode/*.h) 

RES_SOURCES = $(wildcard appl/src/source/*.c)
RES_OBJFILES = $(RES_SOURCES:%.c=%.o)

OBJFILES = $(SOURCES:%.c=%.o)

.PHONY: clean install $(TIMESTAMP_FILE)

all:	dm365

dm365:	dm365_al

dm365_al:	$(TARGET)

install:	$(if $(wildcard $(TARGET)), install_$(TARGET))

install_$(TARGET):
	@install -d $(EXEC_DIR)
	@install $(TARGET) $(EXEC_DIR)
	@install daemon/daemon $(EXEC_DIR)
	@echo
	@echo Installed $(TARGET) binaries to $(EXEC_DIR)..

$(TARGET):	$(TIMESTAMP_FILE) $(OBJFILES) $(XDC_LFILE) appl/src/source/libpvrres.a ucgui/core/libpvrguicore.a
	@echo
	@echo Linking $@ from $^..
	$(LINK.c) -o $@ $^
	$(MAKE) -C daemon all

appl/src/source/libpvrres.a : $(RES_OBJFILES)
	$(AR) rs $@  $^
	
	gcc ++

$(TIMESTAMP_FILE):
	@date +'#define PVR_DATE "%m-%d-%y"' > $@
	@date +'#define PVR_TIME "%T"' >> $@

$(OBJFILES):	%.o: %.c $(HEADERS) $(XDC_CFLAGS)
	@echo Compiling $@ from $<..
	$(COMPILE.c) $(shell cat $(XDC_CFLAGS)) -o $@ $<

$(XDC_LFILE) $(XDC_CFLAGS):	$(XDC_CFGFILE)
	@echo
	@echo ======== Building $(TARGET) ========
	@echo Configuring application using $<
	@echo
	$(VERBOSE) PLATFORM_XDC="$(PLATFORM_XDC)" XDCPATH="$(XDC_PATH)" $(CONFIGURO) -c $(MVTOOL_DIR) -o $(XDC_CFG) -t $(PLATFORM_XDC_TARGET) -p $(PLATFORM_XDC) -b $(DMAI_INSTALL_DIR)/packages/config.bld $(XDC_CFGFILE)

clean:
	@echo Removing generated files..
	$(VERBOSE) -$(RM) -rf $(XDC_CFG) $(OBJFILES) $(TARGET) *~ *.d .dep
	$(MAKE) -C daemon/ clean
