#ifndef PVR_ERR_HEADER
#define PVR_ERR_HEADER

#define ENCODER_ERR(x)  (0xff000000|x)
#define COMMON_ERR(x) (0xfe000000|x)
#define GUI_ERR(x) (0xfd000000|x)
#define DECODE_ERR(x) (0xfc000000|x)

#define ERR_OK	0

#define ERR_OPENFILE COMMON_ERR(1)
#define ERR_WRITEFILE	COMMON_ERR(2)
#define ERR_MALLOC		COMMON_ERR(3)
#define ERR_HEAP_MALLOC COMMON_ERR(4)
#define ERR_SEEKFILE	COMMON_ERR(5)
#define ERR_ERR_POSTSEM COMMON_ERR(6)
#define ERR_READFILE COMMON_ERR(7)

#define ERR_GETFRAME DECODE_ERR(7)
#define ERR_AUDIOINIT DECODE_ERR(8)

#define ERR_AVIGETHEADER DECODE_ERR(12)
#define ERR_AVIGETFRAME DECODE_ERR(13)
#define ERR_AVIFILEEND	DECODE_ERR(14)
#define ERR_NOVFRAME DECODE_ERR(15)
#define ERR_MP3DECODER DECODE_ERR(16)
#define ERR_INVALID_PARSER DECODE_ERR(20)
#define ERR_INVALID_DEC_STATE DECODE_ERR(21)
#define ERR_UNKNOWN_FILEFORAMT DECODE_ERR(22)
#define ERR_NOT_COMPLETE_FILE DECODE_ERR(23)
#define ERR_NOT_SUPPORT_VIDEO_FORMAT DECODE_ERR(24)
#define ERR_NOT_SUPPORT_AUDIO_FORMAT DECODE_ERR(25)

#define ERR_SYNCHRONIZATION DECODE_ERR(26)

#define ERR_POSTMSG ENCODER_ERR(30)
#define ERR_INVALID_ENC_STATE ENCODER_ERR(31)
#define ERR_SYNC_FLUSH ENCODER_ERR(32)
#define ERR_SYNC_INITIAL ENCODER_ERR(33)
#define ERR_AVIADDVFRAME ENCODER_ERR(34)
#define ERR_AVIADDAFRAME ENCODER_ERR(11)

#define ERR_MP3ENCODER ENCODER_ERR(17)
#define ERR_INVALID_ENC_PARA ENCODER_ERR(18)
#define ERR_INVALID_SYNTH ENCODER_ERR(20)
#define ERR_NO_SUPPORT_ENCODER ENCODER_ERR(35)
#define ERR_ENC_AUDIO_FAILED ENCODER_ERR(36)
#define ERR_ENC_AUDIO_NO_BUFFER ENCODER_ERR(38)
#define ERR_ENC_VIDEO_FAILED ENCODER_ERR(37)
#define ERR_ENC_VIDEO_NO_BUFFER ENCODER_ERR(39)
#define ERR_INVALID_DEVICE ENCODER_ERR(40)
#endif
