#include <stdio.h>
#include <string.h>

#include <config.h>	//Config for platform
#include <UI_Message.h>	//UI message

#include <my_spinit.h>
#include <Task_UI/task_ui_var.h>
#include <Task_UI/pvr_ui_func.h>
#include <File_manager.h>

/* Decoder Part
*/
const int PlaybackSpeedFast[]={
	0,31,62,125,250, 500
};
const int PlaybackSpeedSlow[]={
	0,-500,-250,-125,-62,-31
};



/*	Menu Const
 */
 const int MenuButtonCnt[]={
	BUTTON_CNT_BLANK,			// MENUBLANK
	BUTTON_CNT_FILEBROWSER,		// MENUFILEBROWSER
	BUTTON_CNT_FILEOPERATION,	// MENUFILEOPERATION
    BUTTON_CNT_STORAGEINFO,		// MENUFILECOPYTO
    BUTTON_CNT_CODECSETTING,	// MENUCODECSETTING
	BUTTON_CNT_PLAYBACK,		// MENUPLAYBACK
    BUTTON_CNT_DEVSTATUS,		// MENUDEVSTATMSG
    BUTTON_CNT_SYSTEMUPDATA,	// MENUSYSTEMUPDATA
    BUTTON_CNT_DOFILECOPY,		// MENUDOFILECOPY
	BUTTON_CNT_MESSAGEBOX,		// MENUMESSAGEBOX

	BUTTON_CNT_SYSTEMFUNC,		// MENUSYSTEMFUNC
	BUTTON_CNT_UDISKFILELIST,	// MENUUDISKFILELIST

    BUTTON_CNT_LANGUAGE,        //zqh 2015年3月31日 add

//    BUTTON_CNT_MOUNTCF,         // MENUMOUNTCF
};

int MenuButtonMaskBitmap[]={
	BUTTON_MASK_BLANK,			//MENUBLANK
	BUTTON_MASK_FILEBROWSER,	//MENUFILEBROWSER
	BUTTON_MASK_FILEOPERATION,	//MENUFILEOPERATION
	BUTTON_MASK_COPYTO,			//MENUFILECOPYTO
    BUTTON_MASK_CODECSETTING,	//MENUCODECSETTING
	BUTTON_MASK_PLAYBACK,		//MENUPLAYBACK
    BUTTON_MASK_DEVSTATUS,		//MENUDEVSTATMSG
    BUTTON_MASK_SYSTEMUPDATA,	//MENUSYSTEMUPDATA
    BUTTON_MASK_DOFILECOPY,		//MENUDOFILECOPY
	BUTTON_MASK_MESSAGEBOX,		//MENUMESSAGEBOX

	BUTTON_MASK_SYSTEMFUNC,		// MENUSYSTEMFUNC
	BUTTON_MASK_UDISKFILELIST,	// MENUUDISKFILELIST

    BUTTON_MASK_LANGUAGE        //zqh add，2015年3月31日
//    BUTTON_MASK_MOUNTCF,        // MENUMOUNTCF
};


int GetResolutionDesAppix(int nResX,int nResY){
	if (nResY<(nResX>>1)){
		return 1;//For Half D1-i
	}
	return 0;
}


